---
name: Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set image tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            IMAGE_TAG="${GITHUB_REF:10}"
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            IMAGE_TAG="latest"
          else
            IMAGE_TAG="${GITHUB_REF:11}"
          fi
          IMAGE_TAG="ghcr.io/${{ github.repository }}:${IMAGE_TAG}"
          echo ::set-output name=tag::${IMAGE_TAG,,}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build and push image
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.tag.outputs.tag }}
